
road_sign_categories = [
    "stop",
    "no entry for vehicles",
    "speed limit",
    "no overtaking",
    "height limit",
    "weight limit",
    "no u turn",
    "no parking",
    "no stopping",
    "no pedestrians",
    "give way",
    "school zone",
    "pedestrian crossing",
    "road work ahead",
    "slippery road",
    "railway crossing",
    "animal crossing",
    "cycle crossing",
    "round about",
    "bumpy road",
    "cross road",
    "steep ascent",
    "steep descent",
    "hospital",
    "gas station"
]