
road_sign_categories = [
    "stop",
    "no entry for vehicles",
    "speed limit",
    "no overtaking",
    "height limit",
    "weight limit",
    "no u turn",
    "no parking",
    "no stopping",
    "no pedestrians",
    "width limit",
    "give way",
    "school zone",
    "pedestrian crossing",
    "road work ahead",
    "slippery road",
    "railway crossing",
    "animal crossing",
    "narrow roads ahead",
    "cycle crossing",
    "round about",
    "bumpy road",
    "cross road",
    "steep ascent",
    "steep descent",
    "dip",
    "left turn",
    "right turn",
    "hospital",
    "gas station"
]